"use strict";

module.exports = {
  // Auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  // Users
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DEACTIVATE: "USER_DEACTIVATE",

  // Aliases
  USER_CREATED: "USER_CREATE",
  USER_UPDATED: "USER_UPDATE",
  USER_DEACTIVATED: "USER_DEACTIVATE",

  // Locations
  LOCATION_CREATE: "LOCATION_CREATE",
  LOCATION_UPDATE: "LOCATION_UPDATE",
  LOCATION_CLOSE: "LOCATION_CLOSE",
  LOCATION_REOPEN: "LOCATION_REOPEN",
  LOCATION_ARCHIVE: "LOCATION_ARCHIVE",

  // Inventory
  INVENTORY_ADJUST: "INVENTORY_ADJUST",

  // Stock flow
  STOCK_REQUEST_CREATE: "STOCK_REQUEST_CREATE",
  STOCK_REQUEST_DECISION: "STOCK_REQUEST_DECISION",
  STOCK_RELEASE: "STOCK_RELEASE",
  STOCK_RETURN: "STOCK_RETURN",

  // Sales
  SALE_CREATE: "SALE_CREATE",
  SALE_MARK: "SALE_MARK",
  SALE_CANCEL: "SALE_CANCEL",

  // Payments & cash
  PAYMENT_RECORD: "PAYMENT_RECORD",
  CASH_IN: "CASH_IN",
  CASH_OUT: "CASH_OUT",
  VERSEMENT: "VERSEMENT",

  // Credit
  CREDIT_CREATED: "CREDIT_CREATED",
  CREDIT_APPROVE: "CREDIT_APPROVE",
  CREDIT_REJECT: "CREDIT_REJECT",
  CREDIT_SETTLED: "CREDIT_SETTLED",

  // Uploads
  UPLOAD_CREATE: "UPLOAD_CREATE",
  UPLOAD_VIEW: "UPLOAD_VIEW",

  // Internal notes / thread actions
  INTERNAL_NOTE_CREATED: "INTERNAL_NOTE_CREATED",
  INTERNAL_NOTE_UPDATED: "INTERNAL_NOTE_UPDATED",
  INTERNAL_NOTE_DELETED: "INTERNAL_NOTE_DELETED",
  INTERNAL_NOTE_PINNED: "INTERNAL_NOTE_PINNED",
  INTERNAL_NOTE_UNPINNED: "INTERNAL_NOTE_UNPINNED",
  INTERNAL_NOTE_RESOLVED: "INTERNAL_NOTE_RESOLVED",
  INTERNAL_NOTE_REOPENED: "INTERNAL_NOTE_REOPENED",

  // Suppliers
  SUPPLIER_CREATE: "SUPPLIER_CREATE",
  SUPPLIER_UPDATE: "SUPPLIER_UPDATE",
  SUPPLIER_DEACTIVATE: "SUPPLIER_DEACTIVATE",
  SUPPLIER_REACTIVATE: "SUPPLIER_REACTIVATE",
  SUPPLIER_DELETE: "SUPPLIER_DELETE",

  // Supplier bills
  SUPPLIER_BILL_CREATE: "SUPPLIER_BILL_CREATE",
  SUPPLIER_BILL_UPDATE: "SUPPLIER_BILL_UPDATE",
  SUPPLIER_BILL_VOID: "SUPPLIER_BILL_VOID",
  SUPPLIER_BILL_DELETE: "SUPPLIER_BILL_DELETE",

  // Supplier bill payments
  SUPPLIER_BILL_PAYMENT_CREATE: "SUPPLIER_BILL_PAYMENT_CREATE",

  // Owner supplier operations
  OWNER_SUPPLIER_CREATE: "OWNER_SUPPLIER_CREATE",
  OWNER_SUPPLIER_UPDATE: "OWNER_SUPPLIER_UPDATE",
  OWNER_SUPPLIER_DEACTIVATE: "OWNER_SUPPLIER_DEACTIVATE",
  OWNER_SUPPLIER_REACTIVATE: "OWNER_SUPPLIER_REACTIVATE",

  // Owner supplier bill operations
  OWNER_SUPPLIER_BILL_CREATE: "OWNER_SUPPLIER_BILL_CREATE",
  OWNER_SUPPLIER_BILL_UPDATE: "OWNER_SUPPLIER_BILL_UPDATE",
  OWNER_SUPPLIER_BILL_VOID: "OWNER_SUPPLIER_BILL_VOID",
  OWNER_SUPPLIER_BILL_PAYMENT_CREATE: "OWNER_SUPPLIER_BILL_PAYMENT_CREATE",
};
