"use strict";

/**
 * Unified Actions / Permissions
 * - Backward compatible with legacy permissions
 * - Explicit CRUD-style actions
 * - Safe across API + UI
 */

const ACTIONS = {
  // =====================
  // Auth
  // =====================
  AUTH_ME: "AUTH_ME",

  // =====================
  // Users
  // =====================
  USER_CREATE: "USER_CREATE",
  USER_VIEW: "USER_VIEW",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  // Dashboards (role-specific)
  ADMIN_DASHBOARD_VIEW: "ADMIN_DASHBOARD_VIEW",
  MANAGER_DASHBOARD_VIEW: "MANAGER_DASHBOARD_VIEW",

  // Legacy
  USER_MANAGE: "USER_MANAGE",

  // =====================
  // Roles / ownership
  // =====================
  OWNER_ONLY: "OWNER_ONLY",

  // =====================
  // Dashboard / Reports
  // =====================
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  DASHBOARD_OWNER_VIEW: "DASHBOARD_OWNER_VIEW",
  REPORT_VIEW: "REPORT_VIEW",
  REPORTS_DOWNLOAD: "REPORTS_DOWNLOAD",

  // =====================
  // Locations
  // =====================
  LOCATION_CREATE: "LOCATION_CREATE",
  LOCATION_VIEW: "LOCATION_VIEW",
  LOCATION_UPDATE: "LOCATION_UPDATE",

  // =====================
  // Notifications
  // =====================
  NOTIFICATION_VIEW: "NOTIFICATION_VIEW",
  NOTIFICATION_MARK_READ: "NOTIFICATION_MARK_READ",

  // =====================
  // Products
  // =====================
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_EDIT: "PRODUCT_EDIT",
  PRODUCT_PRICE_SET: "PRODUCT_PRICE_SET",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_PRICING_UPDATE: "PRODUCT_PRICING_UPDATE",

  // Owner cross-branch products
  OWNER_PRODUCTS_SUMMARY_VIEW: "OWNER_PRODUCTS_SUMMARY_VIEW",
  OWNER_PRODUCTS_VIEW: "OWNER_PRODUCTS_VIEW",
  OWNER_PRODUCT_BRANCHES_VIEW: "OWNER_PRODUCT_BRANCHES_VIEW",
  OWNER_PRODUCT_CREATE: "OWNER_PRODUCT_CREATE",
  OWNER_PRODUCT_PRICING_UPDATE: "OWNER_PRODUCT_PRICING_UPDATE",
  OWNER_PRODUCT_ARCHIVE: "OWNER_PRODUCT_ARCHIVE",
  OWNER_PRODUCT_RESTORE: "OWNER_PRODUCT_RESTORE",

  // Legacy
  PRODUCT_PRICING_MANAGE: "PRODUCT_PRICING_MANAGE",

  // =====================
  // Customers
  // =====================
  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",

  // =====================
  // Inventory
  // =====================
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_CREATE: "INVENTORY_CREATE",
  INVENTORY_ADJUST: "INVENTORY_ADJUST",
  INVENTORY_MANAGE: "INVENTORY_MANAGE",

  // Owner cross-branch inventory
  OWNER_INVENTORY_SUMMARY_VIEW: "OWNER_INVENTORY_SUMMARY_VIEW",
  OWNER_INVENTORY_VIEW: "OWNER_INVENTORY_VIEW",
  OWNER_PRODUCT_INVENTORY_VIEW: "OWNER_PRODUCT_INVENTORY_VIEW",

  // =====================
  // Inventory arrivals
  // =====================
  INVENTORY_ARRIVAL_CREATE: "INVENTORY_ARRIVAL_CREATE",
  INVENTORY_ARRIVAL_VIEW: "INVENTORY_ARRIVAL_VIEW",

  // =====================
  // Goods receipts
  // =====================
  GOODS_RECEIPT_CREATE: "GOODS_RECEIPT_CREATE",
  GOODS_RECEIPT_VIEW: "GOODS_RECEIPT_VIEW",

  // =====================
  // Inventory adjustment requests
  // =====================
  INVENTORY_ADJUST_REQUEST_CREATE: "INVENTORY_ADJUST_REQUEST_CREATE",
  INVENTORY_ADJUST_REQUEST_VIEW: "INVENTORY_ADJUST_REQUEST_VIEW",
  INVENTORY_ADJUST_REQUEST_DECIDE: "INVENTORY_ADJUST_REQUEST_DECIDE",

  // Legacy short names
  INV_ADJ_REQ_CREATE: "INV_ADJ_REQ_CREATE",
  INV_ADJ_REQ_VIEW: "INV_ADJ_REQ_VIEW",
  INV_ADJ_REQ_DECIDE: "INV_ADJ_REQ_DECIDE",

  // =====================
  // Stock requests / movement
  // =====================
  STOCK_REQUEST_CREATE: "STOCK_REQUEST_CREATE",
  STOCK_REQUEST_VIEW: "STOCK_REQUEST_VIEW",
  STOCK_REQUEST_DECIDE: "STOCK_REQUEST_DECIDE",

  // Confirmations
  STOCK_RELEASE_CONFIRM: "STOCK_RELEASE_CONFIRM",
  STOCK_RETURN_CONFIRM: "STOCK_RETURN_CONFIRM",

  // Used by /requests/:id/release route
  STOCK_RELEASE_TO_SELLER: "STOCK_RELEASE_TO_SELLER",

  // Legacy
  STOCK_REQUEST_APPROVE: "STOCK_REQUEST_APPROVE",
  STOCK_REQUEST_DECLINE: "STOCK_REQUEST_DECLINE",
  STOCK_REQUEST_RELEASE: "STOCK_REQUEST_RELEASE",

  // =====================
  // Holdings
  // =====================
  HOLDINGS_VIEW: "HOLDINGS_VIEW",
  HOLDINGS_ADJUST: "HOLDINGS_ADJUST",
  HOLDINGS_REQUEST_CREATE: "HOLDINGS_REQUEST_CREATE",
  HOLDINGS_REQUEST_VIEW: "HOLDINGS_REQUEST_VIEW",
  HOLDINGS_REQUEST_DECIDE: "HOLDINGS_REQUEST_DECIDE",

  // =====================
  // Sales
  // =====================
  SALE_CREATE: "SALE_CREATE",
  SALE_VIEW: "SALE_VIEW",
  SALE_FULFILL: "SALE_FULFILL",
  SALE_MARK: "SALE_MARK",
  SALE_CANCEL: "SALE_CANCEL",

  // =====================
  // Payments / Cash
  // =====================
  PAYMENT_RECORD: "PAYMENT_RECORD",
  PAYMENT_VIEW: "PAYMENT_VIEW",

  // Owner money / owner payments
  OWNER_PAYMENTS_VIEW: "OWNER_PAYMENTS_VIEW",

  CASH_SESSION_VIEW: "CASH_SESSION_VIEW",
  CASH_SESSION_OPEN: "CASH_SESSION_OPEN",
  CASH_SESSION_CLOSE: "CASH_SESSION_CLOSE",

  CASH_DEPOSIT_VIEW: "CASH_DEPOSIT_VIEW",
  CASH_DEPOSIT_CREATE: "CASH_DEPOSIT_CREATE",

  EXPENSE_VIEW: "EXPENSE_VIEW",
  EXPENSE_CREATE: "EXPENSE_CREATE",
  EXPENSE_VOID: "EXPENSE_VOID",

  CASH_RECONCILE_VIEW: "CASH_RECONCILE_VIEW",
  CASH_RECONCILE_CREATE: "CASH_RECONCILE_CREATE",

  CASH_REPORT_VIEW: "CASH_REPORT_VIEW",

  // Legacy
  CASH_LEDGER_MANAGE: "CASH_LEDGER_MANAGE",
  CASH_LEDGER_VIEW: "CASH_LEDGER_VIEW",

  // =====================
  // Owner loans
  // =====================
  OWNER_LOAN_SUMMARY_VIEW: "OWNER_LOAN_SUMMARY_VIEW",
  OWNER_LOAN_VIEW: "OWNER_LOAN_VIEW",
  OWNER_LOAN_CREATE: "OWNER_LOAN_CREATE",
  OWNER_LOAN_UPDATE: "OWNER_LOAN_UPDATE",
  OWNER_LOAN_REPAYMENT_CREATE: "OWNER_LOAN_REPAYMENT_CREATE",
  OWNER_LOAN_VOID: "OWNER_LOAN_VOID",

  // =====================
  // Credits
  // =====================
  CREDIT_CREATE: "CREDIT_CREATE",
  CREDIT_VIEW: "CREDIT_VIEW",
  CREDIT_DECIDE: "CREDIT_DECIDE",
  CREDIT_SETTLE: "CREDIT_SETTLE",

  // Legacy
  CREDIT_READ: "CREDIT_READ",

  // =====================
  // Refunds
  // =====================
  REFUND_CREATE: "REFUND_CREATE",
  REFUND_VIEW: "REFUND_VIEW",

  // =====================
  // Uploads (files)
  // =====================
  UPLOAD_CREATE: "UPLOAD_CREATE",
  UPLOAD_VIEW: "UPLOAD_VIEW",

  // =====================
  // Audit / Messages
  // =====================
  AUDIT_VIEW: "AUDIT_VIEW",
  MESSAGE_CREATE: "MESSAGE_CREATE",
  MESSAGE_VIEW: "MESSAGE_VIEW",

  // =====================
  // Suppliers (procurement)
  // =====================
  SUPPLIER_CREATE: "SUPPLIER_CREATE",
  SUPPLIER_VIEW: "SUPPLIER_VIEW",
  SUPPLIER_UPDATE: "SUPPLIER_UPDATE",
  SUPPLIER_DELETE: "SUPPLIER_DELETE",

  SUPPLIER_BILL_CREATE: "SUPPLIER_BILL_CREATE",
  SUPPLIER_BILL_VIEW: "SUPPLIER_BILL_VIEW",
  SUPPLIER_BILL_UPDATE: "SUPPLIER_BILL_UPDATE",
  SUPPLIER_BILL_DELETE: "SUPPLIER_BILL_DELETE",

  SUPPLIER_BILL_PAYMENT_CREATE: "SUPPLIER_BILL_PAYMENT_CREATE",
  SUPPLIER_REPORT_VIEW: "SUPPLIER_REPORT_VIEW",

  // =====================
  // Purchase orders
  // =====================
  PURCHASE_ORDER_VIEW: "PURCHASE_ORDER_VIEW",
  PURCHASE_ORDER_CREATE: "PURCHASE_ORDER_CREATE",
  PURCHASE_ORDER_UPDATE: "PURCHASE_ORDER_UPDATE",
  PURCHASE_ORDER_APPROVE: "PURCHASE_ORDER_APPROVE",
  PURCHASE_ORDER_CANCEL: "PURCHASE_ORDER_CANCEL",
};

/**
 * Alias map for backward compatibility & migrations
 */
ACTIONS.__ALIASES__ = {
  USER_MANAGE: ["USER_UPDATE", "USER_DELETE"],

  PRODUCT_PRICING_MANAGE: ["PRODUCT_PRICE_SET"],

  PRODUCT_EDIT: [
    "PRODUCT_UPDATE",
    "PRODUCT_PRICING_UPDATE",
    "PRODUCT_PRICE_SET",
  ],

  REPORT_VIEW: ["REPORTS_DOWNLOAD"],

  INV_ADJ_REQ_CREATE: ["INVENTORY_ADJUST_REQUEST_CREATE"],
  INV_ADJ_REQ_VIEW: ["INVENTORY_ADJUST_REQUEST_VIEW"],
  INV_ADJ_REQ_DECIDE: ["INVENTORY_ADJUST_REQUEST_DECIDE"],

  STOCK_REQUEST_APPROVE: ["STOCK_REQUEST_DECIDE"],
  STOCK_REQUEST_DECLINE: ["STOCK_REQUEST_DECIDE"],

  STOCK_REQUEST_RELEASE: ["STOCK_RELEASE_TO_SELLER", "STOCK_RELEASE_CONFIRM"],

  CREDIT_READ: ["CREDIT_VIEW"],

  // Keep goods receipt routes backward-compatible with current inventory arrival
  // permission setup while we transition to explicit procurement permissions.
  GOODS_RECEIPT_CREATE: [
    "INVENTORY_ARRIVAL_CREATE",
    "INVENTORY_CREATE",
    "PURCHASE_ORDER_VIEW",
  ],
  GOODS_RECEIPT_VIEW: [
    "INVENTORY_ARRIVAL_VIEW",
    "INVENTORY_VIEW",
    "PURCHASE_ORDER_VIEW",
  ],

  // Owner loans compatibility with broader payment/cash permissions
  OWNER_LOAN_VIEW: ["PAYMENT_VIEW", "CASH_REPORT_VIEW"],
  OWNER_LOAN_SUMMARY_VIEW: ["PAYMENT_VIEW", "CASH_REPORT_VIEW"],
  OWNER_LOAN_CREATE: ["PAYMENT_RECORD", "CASH_DEPOSIT_CREATE"],
  OWNER_LOAN_UPDATE: ["PAYMENT_RECORD"],
  OWNER_LOAN_REPAYMENT_CREATE: ["PAYMENT_RECORD", "CASH_DEPOSIT_CREATE"],
  OWNER_LOAN_VOID: ["EXPENSE_VOID", "CASH_LEDGER_MANAGE"],
};

module.exports = Object.freeze(ACTIONS);
