const ROLES = require("./roles");
const ACTIONS = require("./actions");

const ALL_ACTION_STRINGS = Object.values(ACTIONS).filter(
  (v) => typeof v === "string",
);

const ALIASES = ACTIONS.__ALIASES__ || {};
const REVERSE_ALIASES = (() => {
  const reverse = {};
  for (const [legacy, targets] of Object.entries(ALIASES)) {
    for (const t of targets) {
      if (!reverse[t]) reverse[t] = new Set();
      reverse[t].add(legacy);
    }
  }
  return reverse;
})();

const policy = {
  // Owner inherits every action that exists — including all future additions.
  [ROLES.OWNER]: [...ALL_ACTION_STRINGS],

  [ROLES.ADMIN]: [
    ACTIONS.AUTH_ME,
    ACTIONS.DASHBOARD_VIEW,
    ACTIONS.DASHBOARD_OWNER_VIEW,
    ACTIONS.REPORT_VIEW,
    ACTIONS.REPORTS_DOWNLOAD,
    ACTIONS.AUDIT_VIEW,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    ACTIONS.USER_CREATE,
    ACTIONS.USER_VIEW,
    ACTIONS.USER_UPDATE,
    ACTIONS.USER_MANAGE,
    ACTIONS.USER_DELETE,
    ACTIONS.LOCATION_CREATE,
    ACTIONS.LOCATION_VIEW,
    ACTIONS.LOCATION_UPDATE,

    ACTIONS.NOTIFICATION_VIEW,
    ACTIONS.NOTIFICATION_MARK_READ,

    ACTIONS.PRODUCT_CREATE,
    ACTIONS.PRODUCT_VIEW,
    ACTIONS.PRODUCT_UPDATE,
    ACTIONS.PRODUCT_EDIT,
    ACTIONS.PRODUCT_PRICE_SET,
    ACTIONS.PRODUCT_PRICING_UPDATE,
    ACTIONS.PRODUCT_DELETE,

    ACTIONS.INVENTORY_VIEW,
    ACTIONS.INVENTORY_CREATE,
    ACTIONS.INVENTORY_ADJUST,
    ACTIONS.INVENTORY_ARRIVAL_CREATE,
    ACTIONS.INVENTORY_ARRIVAL_VIEW,

    ACTIONS.INVENTORY_ADJUST_REQUEST_CREATE,
    ACTIONS.INVENTORY_ADJUST_REQUEST_VIEW,
    ACTIONS.INVENTORY_ADJUST_REQUEST_DECIDE,

    ACTIONS.STOCK_REQUEST_CREATE,
    ACTIONS.STOCK_REQUEST_VIEW,
    ACTIONS.STOCK_REQUEST_DECIDE,
    ACTIONS.STOCK_RELEASE_TO_SELLER,
    ACTIONS.STOCK_RELEASE_CONFIRM,
    ACTIONS.STOCK_RETURN_CONFIRM,

    ACTIONS.HOLDINGS_VIEW,
    ACTIONS.HOLDINGS_REQUEST_CREATE,
    ACTIONS.HOLDINGS_REQUEST_VIEW,
    ACTIONS.HOLDINGS_REQUEST_DECIDE,

    ACTIONS.CUSTOMER_VIEW,
    ACTIONS.CUSTOMER_CREATE,
    ACTIONS.CUSTOMER_UPDATE,

    ACTIONS.SALE_CREATE,
    ACTIONS.SALE_VIEW,
    ACTIONS.SALE_MARK,
    ACTIONS.SALE_CANCEL,
    ACTIONS.SALE_FULFILL,

    ACTIONS.PAYMENT_RECORD,
    ACTIONS.PAYMENT_VIEW,
    ACTIONS.OWNER_PAYMENTS_VIEW,

    ACTIONS.CREDIT_CREATE,
    ACTIONS.CREDIT_VIEW,
    ACTIONS.CREDIT_DECIDE,
    ACTIONS.CREDIT_SETTLE,

    ACTIONS.REFUND_CREATE,
    ACTIONS.REFUND_VIEW,

    ACTIONS.CASH_SESSION_VIEW,
    ACTIONS.CASH_SESSION_OPEN,
    ACTIONS.CASH_SESSION_CLOSE,
    ACTIONS.CASH_DEPOSIT_VIEW,
    ACTIONS.CASH_DEPOSIT_CREATE,
    ACTIONS.EXPENSE_VIEW,
    ACTIONS.EXPENSE_CREATE,
    ACTIONS.EXPENSE_VOID,
    ACTIONS.CASH_RECONCILE_VIEW,
    ACTIONS.CASH_RECONCILE_CREATE,
    ACTIONS.CASH_REPORT_VIEW,

    ACTIONS.UPLOAD_CREATE,
    ACTIONS.UPLOAD_VIEW,

    ACTIONS.SUPPLIER_CREATE,
    ACTIONS.SUPPLIER_VIEW,
    ACTIONS.SUPPLIER_UPDATE,
    ACTIONS.SUPPLIER_DELETE,
    ACTIONS.SUPPLIER_BILL_CREATE,
    ACTIONS.SUPPLIER_BILL_VIEW,
    ACTIONS.SUPPLIER_BILL_UPDATE,
    ACTIONS.SUPPLIER_BILL_DELETE,
    ACTIONS.SUPPLIER_BILL_PAYMENT_CREATE,
    ACTIONS.SUPPLIER_REPORT_VIEW,

    // Purchase orders — admin can do everything with purchase orders
    ACTIONS.PURCHASE_ORDER_VIEW,
    ACTIONS.PURCHASE_ORDER_CREATE,
    ACTIONS.PURCHASE_ORDER_UPDATE,
    ACTIONS.PURCHASE_ORDER_APPROVE,
    ACTIONS.PURCHASE_ORDER_CANCEL,

    ACTIONS.CASH_LEDGER_MANAGE,
    ACTIONS.CASH_LEDGER_VIEW,

    ACTIONS.ADMIN_DASHBOARD_VIEW,
  ],

  [ROLES.MANAGER]: [
    ACTIONS.AUTH_ME,
    ACTIONS.DASHBOARD_VIEW,
    ACTIONS.REPORT_VIEW,
    ACTIONS.REPORTS_DOWNLOAD,
    ACTIONS.AUDIT_VIEW,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    ACTIONS.NOTIFICATION_VIEW,
    ACTIONS.NOTIFICATION_MARK_READ,

    ACTIONS.PRODUCT_VIEW,
    ACTIONS.PRODUCT_UPDATE,
    ACTIONS.PRODUCT_EDIT,
    ACTIONS.PRODUCT_PRICE_SET,
    ACTIONS.PRODUCT_PRICING_UPDATE,
    ACTIONS.PRODUCT_PRICING_MANAGE,

    ACTIONS.INVENTORY_VIEW,
    ACTIONS.INVENTORY_ARRIVAL_VIEW,
    ACTIONS.INVENTORY_ADJUST_REQUEST_VIEW,
    ACTIONS.INVENTORY_ADJUST_REQUEST_DECIDE,

    ACTIONS.STOCK_REQUEST_VIEW,
    ACTIONS.STOCK_REQUEST_DECIDE,

    ACTIONS.SALE_VIEW,
    ACTIONS.SALE_CANCEL,
    ACTIONS.REFUND_CREATE,
    ACTIONS.REFUND_VIEW,

    ACTIONS.PAYMENT_VIEW,
    ACTIONS.OWNER_PAYMENTS_VIEW,

    ACTIONS.CREDIT_VIEW,
    ACTIONS.CREDIT_DECIDE,

    ACTIONS.CASH_REPORT_VIEW,
    ACTIONS.CASH_RECONCILE_VIEW,
    ACTIONS.CASH_RECONCILE_CREATE,
    ACTIONS.CASH_LEDGER_VIEW,
    ACTIONS.EXPENSE_VIEW,
    ACTIONS.EXPENSE_VOID,

    ACTIONS.USER_VIEW,
    ACTIONS.UPLOAD_VIEW,

    ACTIONS.SUPPLIER_VIEW,
    ACTIONS.SUPPLIER_BILL_CREATE,
    ACTIONS.SUPPLIER_BILL_VIEW,
    ACTIONS.SUPPLIER_BILL_UPDATE,
    ACTIONS.SUPPLIER_REPORT_VIEW,

    // Purchase orders — manager can view, create, update, and approve
    // Cannot cancel (that is an admin-level override)
    ACTIONS.PURCHASE_ORDER_VIEW,
    ACTIONS.PURCHASE_ORDER_CREATE,
    ACTIONS.PURCHASE_ORDER_UPDATE,
    ACTIONS.PURCHASE_ORDER_APPROVE,

    ACTIONS.MANAGER_DASHBOARD_VIEW,
    ACTIONS.CUSTOMER_VIEW,
  ],

  // Store keeper receives goods against purchase orders but does not create,
  // approve, or cancel them. They see the PO list so they know what stock is incoming.
  [ROLES.STORE_KEEPER]: [
    ACTIONS.AUTH_ME,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    ACTIONS.PRODUCT_CREATE,
    ACTIONS.PRODUCT_VIEW,
    ACTIONS.PRODUCT_DELETE,

    ACTIONS.NOTIFICATION_VIEW,
    ACTIONS.NOTIFICATION_MARK_READ,

    ACTIONS.INVENTORY_VIEW,
    ACTIONS.INVENTORY_CREATE,
    ACTIONS.INVENTORY_ARRIVAL_CREATE,
    ACTIONS.INVENTORY_ARRIVAL_VIEW,

    ACTIONS.INVENTORY_ADJUST_REQUEST_CREATE,
    ACTIONS.INVENTORY_ADJUST_REQUEST_VIEW,

    ACTIONS.STOCK_REQUEST_VIEW,
    ACTIONS.STOCK_REQUEST_DECIDE,
    ACTIONS.STOCK_RELEASE_TO_SELLER,
    ACTIONS.STOCK_RELEASE_CONFIRM,
    ACTIONS.STOCK_RETURN_CONFIRM,

    ACTIONS.HOLDINGS_VIEW,

    ACTIONS.SALE_VIEW,
    ACTIONS.SALE_FULFILL,

    // Purchase orders — store keeper can view POs to know what stock is incoming
    ACTIONS.PURCHASE_ORDER_VIEW,

    ACTIONS.UPLOAD_CREATE,
    ACTIONS.UPLOAD_VIEW,

    ACTIONS.STOCK_REQUEST_APPROVE,
  ],

  [ROLES.SELLER]: [
    ACTIONS.AUTH_ME,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    ACTIONS.PRODUCT_VIEW,
    ACTIONS.INVENTORY_VIEW,

    ACTIONS.STOCK_REQUEST_CREATE,
    ACTIONS.STOCK_REQUEST_VIEW,

    ACTIONS.HOLDINGS_VIEW,

    ACTIONS.CUSTOMER_CREATE,
    ACTIONS.CUSTOMER_VIEW,

    ACTIONS.SALE_CREATE,
    ACTIONS.SALE_VIEW,
    ACTIONS.SALE_MARK,

    ACTIONS.NOTIFICATION_VIEW,
    ACTIONS.NOTIFICATION_MARK_READ,

    ACTIONS.CREDIT_CREATE,
    ACTIONS.CREDIT_VIEW,

    ACTIONS.REFUND_VIEW,
    ACTIONS.UPLOAD_VIEW,
  ],

  [ROLES.CASHIER]: [
    ACTIONS.AUTH_ME,
    ACTIONS.MESSAGE_CREATE,
    ACTIONS.MESSAGE_VIEW,

    ACTIONS.SALE_VIEW,
    ACTIONS.CUSTOMER_VIEW,
    ACTIONS.PRODUCT_VIEW,

    ACTIONS.PAYMENT_RECORD,
    ACTIONS.PAYMENT_VIEW,

    ACTIONS.CASH_SESSION_VIEW,
    ACTIONS.CASH_SESSION_OPEN,
    ACTIONS.CASH_SESSION_CLOSE,

    ACTIONS.CASH_DEPOSIT_VIEW,
    ACTIONS.CASH_DEPOSIT_CREATE,

    ACTIONS.EXPENSE_VIEW,
    ACTIONS.EXPENSE_CREATE,

    ACTIONS.CASH_RECONCILE_VIEW,
    ACTIONS.CASH_RECONCILE_CREATE,

    ACTIONS.REFUND_VIEW,

    ACTIONS.NOTIFICATION_VIEW,
    ACTIONS.NOTIFICATION_MARK_READ,

    ACTIONS.UPLOAD_VIEW,

    ACTIONS.CREDIT_VIEW,
    ACTIONS.CREDIT_SETTLE,

    ACTIONS.REFUND_CREATE,

    ACTIONS.CASH_LEDGER_VIEW,
  ],
};

function can(role, action) {
  const allowed = policy[role] || [];
  if (!action) return false;

  if (allowed.includes(action)) return true;

  const forward = ALIASES[action];
  if (Array.isArray(forward) && forward.some((a) => allowed.includes(a))) {
    return true;
  }

  const reverseSet = REVERSE_ALIASES[action];
  if (reverseSet) {
    for (const legacy of reverseSet) {
      if (allowed.includes(legacy)) return true;
    }
  }

  return false;
}

module.exports = { policy, can };
